In [34]:
! pip install numpy

In [35]:
# one dimensional array
import numpy as np

In [41]:
f = np.eye(1)
print(f)

[[1.]]


In [114]:
np.zeros((6,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [116]:
np.ones((7,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [37]:
np.random.random((1,1))


array([[0.38000524]])

In [13]:
t = np.arange(100,1000,50)
print(t)

[100 150 200 250 300 350 400 450 500 550 600 650 700 750 800 850 900 950]


In [16]:
s = np.linspace(5,20,10)
print(s)

[ 5.          6.66666667  8.33333333 10.         11.66666667 13.33333333
 15.         16.66666667 18.33333333 20.        ]


In [45]:
# two dimensional arrays
arr = np.array([[1,2,3,4,5],
               [6,7,8,9,10]])
print(arr.shape)

(2, 5)


In [46]:
a =np.array([[9,2,6,1],
             [2,9,0,1],
             [6,7,3,10],
             [4,6,4,5]])
print(a.size)

16


In [49]:
x = np.array([[77,8,9],
              [56,12,74],
              [67,98,10],
              [23,12,7],
              [21,23,31]])
len(x)

5

In [58]:
num = np.array([[1,3,67,54],
                [89,56,23,0],
                [23,90,78,12],
                [99,23,12,0],
                [78,2,4,89]])
print(num.shape)

(5, 4)


In [68]:
x= np.full((6,4),7)
print(x)
print(x.ndim)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
2


In [73]:
r=np.random.random((7,4))
print(r)

[[0.49614125 0.58802292 0.3302283  0.08002604]
 [0.60459107 0.72406391 0.44691601 0.59343363]
 [0.69540782 0.56271107 0.80029956 0.48754985]
 [0.06584132 0.32152647 0.93382533 0.27710553]
 [0.21009093 0.35150931 0.27771517 0.10850783]
 [0.47780527 0.82035547 0.12877878 0.7116326 ]
 [0.61656589 0.20451836 0.00736659 0.44334109]]


In [107]:
a =np.array([[9,2,6,1],
             [2,9,0,1],
             [6,7,3,10],
             [4,6,4,5]])
print(a.ndim)

2


In [89]:
# three dimensional array
arr = np.array([[[1,2,3,4,5],
               [6,7,8,9,10]]])
                
print(arr.shape)

(1, 2, 5)


In [88]:
num = np.array([[[1,3,67,54],
                [89,56,23,0],
                [23,90,78,12]],
                 
                [[99,23,12,0],
                [78,2,4,89],
                [9,8,1,4]]])
print(num.shape)

(2, 3, 4)


In [90]:
dim = np.array([[[23,45],
                 [23,67],
                 [45,12]],

                [[34,56],
                 [12,34],
                 [0,90]]])
print(dim.size)

12


In [101]:
m = np.array([[[12,34,56],
                [45,12,56],
                [90,89,97],
                [34,67,54],
                [67,89,13]]])
print(m.ndim)

3


In [106]:
m = np.array([[[12,34,56],
                [45,12,56],
                [90,89,97],
                [34,67,54],
                [67,89,13]]])
len(m)

1