In [1]:
# sub of a two elements in a list
list = [1,2,3,4,5,6,7,8]
print(list[1]-list[3])

-2


In [2]:
# adding of a two elements in a list
print(list[-2]+list[-5])

11


In [3]:
# multiplication of a two elements in a list
print(list[5]*list[7])

48


In [4]:
# division a two elements in a list
print(list[3]/list[5])

0.6666666666666666


In [6]:
# modulus of a two elements in a list
print(list[6]% list[1])

1


In [39]:
list1 = [23,42,67,90,123]
list2 = [45,78,12,34,56,27,89]
print(list1[4]+ list2[5])

150


In [40]:
print(list[-3]-list2[-2])

-21


In [12]:
# 3D dimensional array
import numpy as np
arr = np.array([[[9,2,3,4],
                 [4,6,0,1],
                 [6,2,1,7],
                 [5,3,7,9]]])
print(arr[0:4,2,3])

[7]


In [21]:
arr = np.array([[[89,34,23],
                 [71,23,50],
                 [32,42,10]]])

                
print(arr[0:3,2,1])

[42]


In [26]:
s = np.array([[[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15]],

              [[16,17,18,19,20],
               [21,22,23,24,25],
               [26,27,28,29,30]]])
print(s[0:5, :, :] )

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]


In [27]:
print(s[0, :, :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [38]:
print(s[0:5, 2 ,3]) 

[14 29]
